In [231]:
import pandas as pd
import seaborn as sns
import numpy as np

In [232]:
movies = pd.read_csv('datasets/tmdb_5000_movies.csv')
credits = pd.read_csv('datasets/tmdb_5000_credits.csv')

In [233]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [234]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [235]:
movie_df = movies.merge(credits, 
                   on='title',)
print(movies.shape)
print(credits.shape)
print(merged_df.shape)

(4803, 20)
(4803, 4)
(4809, 23)

In [236]:
movie_df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

not imp - budget, homepage, original title, original_language, popularity
imp - genre,id,keywords,title,overview,cast,crew

In [237]:
movie_df = movie_df[['movie_id','title','genres','keywords','overview','cast','crew']]

In [238]:
movie_df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [239]:
movie_df.isnull().sum()

movie_id    0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [240]:
movie_df.dropna(inplace=True)

In [241]:
movie_df.duplicated().sum()

0

In [242]:
import ast
def convert(list_of_dict):
    return [i['name'] for i in ast.literal_eval(list_of_dict)]

In [243]:
movie_df['genres'] = movie_df['genres'].apply(convert)
movie_df['keywords'] = movie_df['keywords'].apply(convert)

In [244]:
movie_df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [245]:
import ast
def convert_cast(list_of_dict):
    return [i['name'] for i in ast.literal_eval(list_of_dict)][0:3]

movie_df['cast'] = movie_df['cast'].apply(convert_cast)

In [246]:
import ast
def convert_cast(list_of_dict):
    return [i['name'] for i in ast.literal_eval(list_of_dict) if i['job'] == 'Director' ]

movie_df['crew'] = movie_df['crew'].apply(convert_cast)

In [247]:
movie_df.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [248]:
movie_df['overview'] = movie_df['overview'].apply(lambda x:x.split())

In [249]:
movie_df.head(3)

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [250]:
movie_df['genres'] = movie_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movie_df['keywords'] = movie_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movie_df['overview']=movie_df['overview'].apply(lambda x:[i.replace(" ","") for i in x])
movie_df['cast'] = movie_df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movie_df['crew'] = movie_df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [251]:
movie_df['tags'] = movie_df['overview']+movie_df['genres']+movie_df['keywords']+movie_df['cast']+movie_df['crew']

In [252]:
mov_df = movie_df[['movie_id','title','tags']]
mov_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [253]:
mov_df['tags'] = mov_df['tags'].apply(lambda x:" ".join(x))
mov_df['tags'][0]

C:\Users\DELL\AppData\Local\Temp\ipykernel_4524\878889883.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov_df['tags'] = mov_df['tags'].apply(lambda x:" ".join(x))

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [254]:
mov_df['tags'] = mov_df['tags'].apply(lambda x:x.lower())

C:\Users\DELL\AppData\Local\Temp\ipykernel_4524\932319333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov_df['tags'] = mov_df['tags'].apply(lambda x:x.lower())

In [277]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(mov_df['tags']).toarray()

In [274]:
cv.get_feature_names_out()[:1000]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940', '1944', '1950', '1950s', '1960', '1960s', '1970',
       '1970s', '1971', '1974', '1976', '1980', '1985', '1990', '1999',
       '19th', '19thcenturi', '20', '200', '2003', '2009', '20th', '21st',
       '23', '24', '25', '30', '300', '3d', '40', '50', '500', '60', '70',
       '80', 'aaron', 'aaroneckhart', 'abandon', 'abduct',
       'abigailbreslin', 'abil', 'abl', 'aboard', 'abov', 'abu', 'academ',
       'academi', 'accept', 'access', 'accid', 'accident', 'acclaim',
       'accompani', 'accomplish', 'account', 'accu', 'ace', 'achiev',
       'acquaint', 'act', 'action', 'actionhero', 'activ', 'activist',
       'activities', 'actor', 'actress', 'actual', 'ad', 'adam',
       'adamsandl', 'adamshankman', 'adapt', 'add', 'addict', 'adjust',
       'admir', 'admit', 'adolesc', 'adopt', 'ador', 'adrienbrodi',
       'adult', 'adultanim', 'adulteri', 'adulthood', 'advanc',
       'adventur', 'adventure', 'adventures', 'adverti', 'advi', 'advic',
       'affair', 'affect', 'afghanistan', 'africa', 'african',
       'africanamerican', 'aftercreditsst', 'afterlif', 'aftermath', 'ag',
       'age', 'agediff', 'agenc', 'agency', 'agenda', 'agent', 'agents',
       'aggress', 'ago', 'agr', 'ahead', 'aid', 'aidanquinn', 'ail',
       'aim', 'air', 'airplan', 'airplanecrash', 'airport', 'aka', 'al',
       'alabama', 'alan', 'alaska', 'albert', 'alcatraz', 'alcohol',
       'alecbaldwin', 'alex', 'alexkendrick', 'alfredhitchcock', 'ali',
       'alic', 'alice', 'alien', 'alieninva', 'alienlife', 'alienplanet',
       'aliens', 'alik', 'aliv', 'alive', 'allen', 'alli', 'allianc',
       'allow', 'alon', 'alongsid', 'alpacino', 'alpha', 'alreadi',
       'alter', 'altern', 'alway', 'alyssa', 'alzheimer', 'amanda',
       'amandapeet', 'amandaseyfri', 'amateur', 'amaz', 'amazon',
       'ambassador', 'ambit', 'ambiti', 'ambul', 'ambush', 'america',
       'american', 'americanabroad', 'americancivilwar', 'americanfootb',
       'americanfootballplay', 'amid', 'amidst', 'amnesia', 'amp',
       'amsterdam', 'amu', 'amusementpark', 'amy', 'amyadam', 'amysmart',
       'ana', 'anakin', 'analyst', 'anarchiccomedi', 'ancient',
       'ancientrom', 'ancientworld', 'anderson', 'andi', 'andiemacdowel',
       'andrew', 'android', 'andy', 'andygarcía', 'angel', 'angela',
       'angelabassett', 'angeles', 'angelinajoli', 'anger', 'angl',
       'angri', 'ani', 'anim', 'animalattack', 'animalhorror', 'animals',
       'anjelicahuston', 'ann', 'anna', 'annafari', 'annakendrick',
       'anne', 'annehathaway', 'annemoss', 'annetteben', 'anni', 'annie',
       'announc', 'annual', 'anonym', 'anoth', 'answer', 'ant',
       'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin',
       'anthonymacki', 'anthropomorph', 'anti', 'antic', 'antihero',
       'antiqu', 'antoinefuqua', 'antoniobandera', 'antonyelchin',
       'anyon', 'anyth', 'apart', 'apartheid', 'apartment', 'ape',
       'apocalyp', 'apocalypse', 'apocalypt', 'appar', 'appear', 'appl',
       'apple', 'appoint', 'appreci', 'apprent', 'approach', 'april',
       'aquarium', 'arab', 'arch', 'archaeologist', 'archeolog', 'archer',
       'architect', 'arctic', 'area', 'aren', 'arena', 'argument', 'ari',
       'aristocrat', 'arm', 'armi', 'armor', 'armsdeal', 'army', 'arnold',
       'arnoldschwarzenegg', 'arrang', 'arrangedmarriag', 'arrest',
       'arriv', 'arrog', 'art', 'arthur', 'artifact', 'artifici',
       'artificialintellig', 'artist', 'ash', 'ashley', 'ashleyjudd',
       'ashtonkutch', 'asia', 'asian', 'asid', 'ask', 'aspect', 'aspir',
       'assassin', 'assault', 'assembl', 'assign', 'assist', 'assistant',
       'associ', 'assum', 'asteroid', 'astronaut', 'asylum', 'atheist',
       'athlet', 'atom', 'atomicbomb', 'attack', 'attacks', 'attempt',
       'attempttoescap', 'attend', 'attent', 'attic', 'attitud',
       'attorney', 'attract', 'auction', 'audienc', 'audit', 'august',
       'aunt', 'austin', 'australia', 'australian', 'author', 'autism',
       'auto', 'automobilerac', 'aveng', 'averag', 'avoid', 'await',
       'awak', 'awaken', 'awar', 'award', 'away', 'awkward', 'awri',
       'awry', 'ax', 'ba', 'babe', 'babi', 'baby', 'bachelor', 'backdrop',
       'background', 'backpack', 'bad', 'bag', 'bahama', 'bail', 'balanc',
       'ball', 'ballet', 'balloon', 'baltimor', 'ban', 'band', 'bandit',
       'bangkok', 'banish', 'bank', 'banker', 'bankrobb', 'bankrobberi',
       'bar', 'barbrastreisand', 'bare', 'bargain', 'barn', 'barney',
       'baron', 'barri', 'barrier', 'barrylevinson', 'barrysonnenfeld',
       'base', 'baseb', 'basedoncomicbook', 'basedongraphicnovel',
       'basedonnovel', 'basedonplay', 'basedonstagemu', 'basedontrueev',
       'basedontruestori', 'basedontvseri', 'basedonvideogam',
       'basedonyoungadultnovel', 'basement', 'basketb', 'basketball',
       'bat', 'batman', 'battl', 'battle', 'battlefield', 'bay', 'beach',
       'beam', 'bear', 'beard', 'beast', 'beat', 'beauti', 'beautiful',
       'beautifulwoman', 'beauty', 'becam', 'becau', 'becki', 'becom',
       'becominganadult', 'bed', 'bedroom', 'bee', 'beer', 'befor',
       'befriend', 'began', 'begin', 'begins', 'behavior', 'belief',
       'believ', 'bell', 'bella', 'belong', 'belov', 'ben', 'benaffleck',
       'bend', 'beneath', 'benefit', 'benfost', 'beniciodeltoro',
       'benjamin', 'benjaminbratt', 'benkingsley', 'bennett', 'benstil',
       'bent', 'berlin', 'best', 'bestfriend', 'bestfriendsinlov', 'bet',
       'beth', 'betray', 'bettemidl', 'better', 'betti', 'beverli',
       'bibl', 'bid', 'big', 'bigger', 'biggest', 'bike', 'biker',
       'bikini', 'billhad', 'billi', 'billionair', 'billmurray',
       'billnighi', 'billpaxton', 'billpullman', 'billybobthornton',
       'billycrudup', 'billycryst', 'biographi', 'biolog', 'bird',
       'birth', 'birthday', 'bisexu', 'bishop', 'bit', 'bite', 'bitter',
       'bizarr', 'black', 'blackmag', 'blackmail', 'blackpeopl',
       'blacksmith', 'blade', 'blame', 'blend', 'blind', 'bliss',
       'blizzard', 'block', 'blond', 'blood', 'bloodi', 'bloodsplatt',
       'bloodthirsti', 'blow', 'blue', 'board', 'boardingschool', 'boat',
       'bob', 'bobbi', 'bobbyfarrelli', 'bobhoskin', 'bodi', 'body',
       'bodyguard', 'bold', 'bollywood', 'bomb', 'bond', 'bone', 'book',
       'border', 'bore', 'boredom', 'born', 'boss', 'boston', 'botch',
       'bound', 'boundari', 'bounti', 'bountyhunt', 'bout', 'box',
       'boxer', 'boy', 'boyfriend', 'boys', 'bradleycoop', 'bradpitt',
       'brain', 'brainwash', 'brand', 'brandon', 'brave', 'braveri',
       'brazil', 'brazilian', 'break', 'breakdown', 'breakup', 'breast',
       'breath', 'breed', 'brendanfra', 'brendangleeson', 'brent',
       'brettratn', 'brian', 'briandepalma', 'bride', 'bridesmaid',
       'bridg', 'brief', 'brielarson', 'brien', 'bright', 'brilliant',
       'bring', 'brink', 'britain', 'british', 'britishsecretserv',
       'brittanymurphi', 'broadcast', 'broadway', 'broke', 'broken',
       'broker', 'bronx', 'brook', 'brooklyn', 'broom', 'brothel',
       'brother', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brought', 'brown', 'bruce',
       'brucegreenwood', 'brucewilli', 'brutal', 'bryans', 'bu', 'buck',
       'bud', 'buddi', 'buddy', 'buddycomedi', 'buddycop', 'budget',
       'build', 'building', 'built', 'bullet', 'bulli', 'bumbl', 'bunch',
       'bunker', 'bunni', 'burglar', 'buri', 'burn', 'bush', 'busi',
       'business', 'businessman', 'bust', 'butcher', 'butler', 'butt',
       'button', 'buy', 'buzz', 'cabin', 'caesar', 'cage', 'cairo', 'cal',
       'california', 'calvin', 'camcord', 'came', 'camera', 'cameraman',
       'camerondiaz', 'camp', 'campaign', 'campbell', 'campu', 'canada',
       'canadian', 'cancer', 'candi', 'candid', 'canin', 'cannib',
       'canuxploit', 'capabl', 'caper', 'capit', 'capt', 'captain',
       'captiv', 'captur', 'capture', 'car', 'caraccid', 'carcha',
       'carcrash', 'card', 'care', 'career', 'carefr', 'caretak',
       'careymulligan', 'caribbean', 'carjourney', 'carl', 'carlagugino',
       'carmen', 'carol', 'carolina', 'carrac', 'carri', 'carrie',
       'cartel', 'carter', 'cartoon', 'caryelw', 'case', 'caseyaffleck',
       'cash', 'casino', 'cast', 'castl', 'cat', 'cataclysm',
       'catastroph', 'catch', 'cateblanchett', 'catherinedeneuv',
       'catherinekeen', 'catherinezeta', 'cathol', 'cattl', 'cau',
       'caught', 'cavalri', 'cave', 'cavemen', 'celebr', 'celebration',
       'cell', 'cellphon', 'cemeteri', 'center', 'centr', 'central',
       'centuri', 'centuries', 'century', 'ceo', 'certain', 'chad',
       'chain', 'chainsaw', 'challeng', 'chamber', 'champion',
       'championship', 'chanc', 'chance', 'chang', 'change', 'changed',
       'changes', 'channingtatum', 'chao', 'chaos', 'chaotic', 'chapter',
       'charact', 'character', 'characters', 'charg', 'charismat',
       'charl', 'charli', 'charlie', 'charliesheen', 'charlizetheron',
       'charm', 'chart', 'chase', 'chauffeur', 'chazzpalminteri', 'cheat',
       'check', 'cheerlead', 'chef', 'chemic', 'cher', 'chevycha',
       'chicago', 'chicken', 'chief', 'child', 'childabu', 'childhero',
       'childhood', 'childprodigi', 'children', 'chill', 'chimp', 'china',
       'chine', 'chip', 'chipmunk', 'chiwetelejiofor', 'chloëgracemoretz',
       'chloësevigni', 'chocol', 'choic', 'choice', 'choo', 'chosen',
       'chowyun', 'chri', 'chriscolumbu', 'chriscoop', 'chrisevan',
       'chrishemsworth', 'chrisklein', 'chrispin', 'chrisrock', 'christ',
       'christian', 'christianb', 'christianslat', 'christin',
       'christinaappleg', 'christinaricci', 'christma', 'christmas',
       'christmasparti', 'christmastr', 'christoph', 'christopherlambert',
       'christopherlloyd', 'christophernolan', 'christopherplumm',
       'christopherwalken', 'christophwaltz', 'chrisweitz', 'chronicl',
       'chuck', 'church', 'cia', 'ciaránhind', 'cigarettesmok',
       'cillianmurphi', 'cinema', 'circl', 'circu', 'circuit', 'circumst',
       'citi', 'citizen', 'city', 'civil', 'civilian', 'civilwar',
       'claim', 'clair', 'clairedan', 'claireforlani', 'clan', 'clark',
       'clash', 'class', 'classdiff', 'classic', 'classmat', 'classroom',
       'claudevandamm', 'clay', 'clean', 'clear', 'clerk', 'clever',
       'client', 'clients', 'cliff', 'climat', 'climb', 'clinteastwood',
       'cliveowen', 'clock', 'clone', 'close', 'closer', 'cloud', 'clown',
       'club', 'clue', 'clueless', 'clutch', 'coach', 'coast', 'cocain',
       'code', 'coffin', 'cohen', 'col', 'cold', 'coldwar', 'cole',
       'colin', 'colinfarrel', 'colinfirth', 'collap', 'colleagu',
       'collect', 'collector', 'colleg', 'college', 'colli', 'collid',
       'colombia', 'colonel', 'coloni', 'color', 'colorado', 'coma',
       'combat', 'combin', 'come', 'comeback', 'comedi', 'comedian',
       'comedy', 'comet', 'comfort', 'comic', 'coming', 'comingofag',
       'comingout', 'command', 'commando', 'commerci', 'commiss',
       'commit', 'common', 'commun', 'communist', 'community', 'compani',
       'companion', 'company', 'compass', 'compet', 'competit',
       'competition', 'complet', 'complex', 'complic', 'compo', 'compul',
       'comput', 'computerviru', 'conan', 'concern', 'concert', 'concoct',
       'condit', 'conduct', 'confed', 'confess', 'confid', 'confin',
       'conflict', 'confront', 'confu', 'congress', 'conman', 'connect',
       'connecticut', 'connel', 'connor', 'conquer', 'consequ',
       'consequences', 'conserv', 'consid', 'conspir', 'conspiraci',
       'conspiracy', 'constant', 'constantli', 'construct', 'consum',
       'contact', 'contain', 'contemporari', 'contend', 'content',
       'contest', 'contin', 'continu', 'contract', 'contractor',
       'control', 'controversi', 'convent', 'conver', 'converg',
       'convict', 'convinc', 'cook'], dtype=object)

In [216]:
pip install nltk

Requirement already satisfied: nltk in c:\users\dell\anaconda3\lib\site-packages (3.7)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: tqdm in c:\users\dell\anaconda3\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: joblib in c:\users\dell\anaconda3\lib\site-packages (from nltk) (1.1.1)
Requirement already satisfied: click in c:\users\dell\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [265]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [266]:
def stem(text):
    stemmed_words = [ps.stem(i) for i in text.split()]
    return " ".join(stemmed_words)

In [268]:
mov_df['tags'] = mov_df['tags'].apply(stem)

C:\Users\DELL\AppData\Local\Temp\ipykernel_4524\1775750723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov_df['tags'] = mov_df['tags'].apply(stem)

In [267]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [280]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [308]:
def recommend(movie):
    mov_index = mov_df[mov_df['title']==movie].index[0]
    distances = similarity[mov_index]
    movies_list = sorted(list(enumerate(distances)),key=lambda x:x[1],reverse=True)[1:6]
    return [mov_df.iloc[i[0]].title for i in movies_list]

In [310]:
recommend('Batman Begins')

['The Dark Knight', 'Batman', 'Batman', 'The Dark Knight Rises', '10th & Wolf']

In [322]:
import pickle

In [329]:
pickle.dump(mov_df.to_dict(),open('movies_dict.pkl','wb'))

In [331]:
pickle.dump(similarity,open('similarity.pkl','wb'))